import { e } from './enum.js'

export const MODELS = [
	{ id: 'Auto', series: 'Auto', label: 'Auto Detect' },
	{ id: 'AW-HE2', series: 'HE2', label: 'AW-HE2' },
	{ id: 'AW-HE20', series: 'UE20', label: 'AW-HE20' },
	{ id: 'AW-HE35', series: 'HE40', label: 'AW-HE35' },
	{ id: 'AW-HE38', series: 'HE40', label: 'AW-HE38' },
	{ id: 'AW-HE40', series: 'HE40', label: 'AW-HE40' },
	{ id: 'AW-HE42', series: 'UE70', label: 'AW-HE42' },
	{ id: 'AW-HE48', series: 'HE40', label: 'AW-HE48' },
	{ id: 'AW-HE50', series: 'HE50', label: 'AW-HE50' },
	{ id: 'AW-HE58', series: 'HE40', label: 'AW-HE58' },
	{ id: 'AW-HE60', series: 'HE50', label: 'AW-HE60' },
	{ id: 'AW-HE65', series: 'HE40', label: 'AW-HE65' },
	{ id: 'AW-HE68', series: 'UE70', label: 'AW-HE68' },
	{ id: 'AW-HE70', series: 'HE40', label: 'AW-HE70' },
	{ id: 'AW-HE75', series: 'UE70', label: 'AW-HE75' },
	{ id: 'AW-HE120', series: 'HE120', label: 'AW-HE120' },
	{ id: 'AW-HE130', series: 'HE130', label: 'AW-HE130' },
	{ id: 'AW-HE145', series: 'UE150', label: 'AW-HE145' },
	{ id: 'AW-HN38', series: 'HE40', label: 'AW-HN38' },
	{ id: 'AW-HN40', series: 'HE40', label: 'AW-HN40' },
	{ id: 'AW-HN65', series: 'HE40', label: 'AW-HN65' },
	{ id: 'AW-HN130', series: 'HE130', label: 'AW-HN130' },
	{ id: 'AW-HR140', series: 'HR140', label: 'AW-HR140' },
	{ id: 'AW-UE4', series: 'UE4', label: 'AW-UE4' },
	{ id: 'AW-UE5', series: 'UE5', label: 'AW-UE5' },
	{ id: 'AW-UE20', series: 'UE20', label: 'AW-UE20' },
	{ id: 'AW-UE30', series: 'UE50', label: 'AW-UE30' },
	{ id: 'AW-UE40', series: 'UE50', label: 'AW-UE40' },
	{ id: 'AW-UE50', series: 'UE50', label: 'AW-UE50' },
	{ id: 'AW-UE63', series: 'UE70', label: 'AW-UE63' },
	{ id: 'AW-UE65', series: 'UE70', label: 'AW-UE65' },
	{ id: 'AW-UE70', series: 'UE70', label: 'AW-UE70' },
	{ id: 'AW-UE80', series: 'UE80', label: 'AW-UE80' },
	{ id: 'AW-UE100', series: 'UE100', label: 'AW-UE100' },
	{ id: 'AW-UR100', series: 'UR100', label: 'AW-UR100' },
	{ id: 'AW-UE150', series: 'UE150', label: 'AW-UE150' },
	{ id: 'AW-UE150A', series: 'UE150A', label: 'AW-UE150A' },
	{ id: 'AW-UE155', series: 'UE150', label: 'AW-UE155' },
	{ id: 'AW-UE160', series: 'UE160', label: 'AW-UE160' },
	{ id: 'AW-UN70', series: 'UE70', label: 'AW-UN70' },
	{ id: 'AW-UN145', series: 'UE150', label: 'AW-UN145' },
	{ id: 'AK-UB10', series: 'UB50', label: 'AK-UB10' },
	{ id: 'AK-UB50', series: 'UB50', label: 'AK-UB50' },
	{ id: 'AK-UB300', series: 'UB300', label: 'AK-UB300' },
	{ id: 'AK-UBX100', series: 'UBX100', label: 'AK-UBX100' },
	{ id: 'AG-CX350', series: 'CX350', label: 'AG-CX350' },
	{ id: 'AG-CX200', series: 'CX350', label: 'AG-CX200' },
	{ id: 'AJ-UPX360', series: 'CX350', label: 'AJ-UPX360' },
	{ id: 'AJ-CX4000', series: 'CX350', label: 'AJ-CX4000' },
	{ id: 'AJ-UPX900', series: 'CX350', label: 'AJ-UPX900' },
	{ id: 'Other', series: 'Other', label: 'Other Cameras' },
]

// The feature set shared by every model. Each series below spreads this and states only what it
// changes, so a series body is exactly the list of ways that model deviates from the norm.
// When integrating a new camera model, start here and override only what differs.
const BASE_CAPABILITIES = {
	audioVolumeLevel: { maxch: 2, min: -40, max: 20, step: 1 }, // Has Audio Volume Level control (OSA:D5)
	chromaLevel: { cmd: 'OCG', dropdown: e.ENUM_CHROMA_LEVEL_3 }, // Has Chroma Level control (OCG)
	chromaPhase: { offset: 0x80, limit: 31, step: 1, hexlen: 2 }, // Has Chroma Phase (OSJ:0B)
	colorGain: { cmd: { red: 'ORI', blue: 'OBI' }, offset: 0x96, limit: 150, step: 1, hexlen: 3 }, // Has numbered red/blue Gain (ORG and OBG)
	colorPedestal: { cmd: { red: 'ORP', blue: 'OBP' }, offset: 0x96, limit: 150, step: 1, hexlen: 3 }, // Has numbered red/blue Pedestal (ORP or OBP)
	colorTemperature: {
		advanced: { inc: 'OSI:1E', dec: 'OSI:1F', set: 'OSI:20', min: 2000, max: 15000, maxStep: 10 },
	}, // Has Color Temperature (OSD:B1 or OSI:20)
	colorbar: true, // Has Color Bar Generator (DCB)
	dnr: { dropdown: e.ENUM_DNR }, // Has Digital Noise Reduction (OSD:3A)
	drs: { dropdown: e.ENUM_DRS }, // Has Dynamic Range Stretch (OSE:33)
	error: true, // Camera can return enumerated error messages (rER)
	errorCamera: { cmd: 'QSI:46', bits: ['Fan', 'High Temperature', 'Lens', 'Pan/Tilt', 'Sensor'] }, // Has error state bitmask (QSI:46 or QER)
	filter: { dropdown: e.ENUM_FILTER_OTHER }, // Has ND Filter Support (OFT)
	filterFollow: false, // Has ND Filter Status (QSJ:D2)
	focus: true, // Has Focus control and position (Fxx and AXFxxx)
	focusAuto: true, // Has (switchable) Auto Focus (OAF)
	focusPushAuto: true, // Has Push Auto Focus feature (OSE:69:1)
	gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_CX350 }, // Has Gain (OGU or OGS)
	imageTransmission: { cmd: 'view.cgi?action=snapshot' }, // Has a JPEG one-shot image request (view.cgi)
	install: true, // Has support for Desktop or Hanging Install Position (iNSx)
	iris: { cmd: 'AXI', transport: 'ptz', offset: 0x555, max: 0xaaa, step: 0x1e }, // Has Iris control and position (#AXI or ORV)
	irisAuto: true, // Has (switchable) Auto Iris (ORS)
	irisF: false, // Has Iris F No. decoding (OIF)
	irisFollowPosition: true, // Has Iris Follow (QSD:4F)
	night: true, // Has Day/Night Mode (d6x)
	ois: { dropdown: e.ENUM_OIS_OTHER }, // Has Optical Image Stabilisation control (OIS)
	panTilt: true, // Has Pan/Tilt Head control (#P, #T, #PTS, #APC)
	panTiltPosition: true, // Reports Pan/Tilt position (#APC query, #PTV)
	panTiltLimit: true, // Has support for movement range limit (#LC)
	pedestal: { cmd: 'OSJ:0F', offset: 0x800, limit: 200, step: 1, hexlen: 3 }, // Has Master Pedestal (OTD, OSJ:0F or OSG:4A)
	poll: false, // Definiton of states that needs to be polled continously from camera (never updated by subscription etc.)
	power: true, // Has Power control and status (px and Ox)
	preset: 100, // Has Preset operations (Mxx, Rxx and Cxx) and states (sXX and qXX)
	presetScope: true, // Has Preset Recall Scope control (OSE:71) - the AW-UE4 has presets but no scope
	presetSpeed: { dropdown: e.ENUM_PRESET_SPEED_TABLE_2 }, // Has Preset Recall Speed control (UPVSxx)
	presetThumbnails: false, // Has support for autogenerated Preset Thumbnails
	presetTime: true, // Has additional Preset Recall Time control (UPVSxx and OSJ:29:1)
	pull: {
		ptz: ['O', 'DA', 'LPI', 'PE00', 'PE01', 'PE02', 'RER', 'S'],
		cam: ['QAW', 'QBR', 'QGU', 'QSA:87', 'QSE:71'],
		web: false,
	}, // States that need to be pulled from the camera if no event subscription is available.
	recordSD: true, // Has SD Card Recording control (sdctrl?save=start or sdctrl?save=end)
	restart: true, // Has Restart command (initial?cmd=reset)
	shootingMode: false, // Has Shooting Mode control (OSI:30)
	shutter: { cmd: 'OSJ:03', inc: 'OSJ:04', dec: 'OSJ:05', dropdown: e.ENUM_SHUTTER_ADV }, // Has Shutter Support (OSH, OSJ:03 - OSJ:06, ...)
	streamRTMP: true, // Has RTMP Push Streaming control (rtmp_ctrl?cmd=start or rtmp_ctrl?cmd=stop)
	streamSRT: true, // Has SRT Caller Streaming control (srt_ctrl?cmd=start or srt_ctrl?cmd=stop)
	streamTS: true, // Has MPEG-TS Output Streaming control (ts_ctrl?cmd=start or ts_ctrl?cmd=stop)
	subscription: true, // Camera supports subscription to TCP-based status update notifications and bulk retreival of initial state (camdata.html)
	tally: true, // Has Red Tally (TLR or DAx)
	tally2: true, // Has Green Tally (TLG)
	tally3: true, // Has Yellow Tally (TLY)
	trackingAuto: true, // Has internal Autotracking features (OSL:B6 - OSL:C2)
	version: true, // Camera provides software version (from initial getinfo or QSV, OSV)
	videoFormat: true, // Camera reports current video format (OSA:87)
	whiteBalance: { dropdown: e.ENUM_WHITEBALANCE, confirm: { 2: '1', 3: '2' } }, // Has White Balance Modes (OAW)
	zoom: true, // Has Zoom control and position (Zxx and AXZxxx)
}

export const SERIES_SPECS = [
	{
		// Basic set of common features. Use this as base when integrating new camera models.
		id: 'Other',
		capabilities: BASE_CAPABILITIES,
	},
	{
		// Specific for the AG-CX350/4000 series
		id: 'CX350',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_99 },
			chromaPhase: false,
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: {
				cmd: { red: 'ORP', blue: 'OBP', green: 'OSJ:10' },
				offset: 0x96,
				limit: 100,
				step: 1,
				hexlen: 3,
			},
			dnr: false,
			drs: false,
			error: false,
			errorCamera: false,
			filter: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_CX350 },
			install: false,
			night: false,
			panTilt: false,
			panTiltPosition: false,
			panTiltLimit: false, // camcorder, no pan/tilt head
			poll: {
				ptz: ['GF', 'GI', 'GZ'],
				cam: [
					'QAF',
					'QAW',
					'QBP',
					'QBR',
					'QFT',
					'QGU',
					'QIS',
					'QLG',
					'QLR',
					'QRP',
					'QRS',
					'QSD:4F',
					'QSD:B0',
					'QSG:39',
					'QSG:3A',
					'QSI:20',
					'QSJ:0F',
					'QSJ:10',
				],
				web: ['get_state'],
			},
			power: false,
			preset: false,
			presetSpeed: false,
			presetTime: false,
			pull: false,
			restart: false,
			shutter: false,
			streamTS: false,
			subscription: false,
			tally3: false,
			trackingAuto: false,
			videoFormat: false,
			whiteBalance: { dropdown: e.ENUM_WHITEBALANCE_CX350 },
		},
	},
	{
		// Specific for the AW-HE2 camera
		id: 'HE2',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: false,
			chromaPhase: false,
			colorGain: false,
			colorPedestal: false,
			colorTemperature: false,
			dnr: false,
			drs: false,
			error: false,
			errorCamera: false,
			filter: false,
			focus: false,
			focusAuto: false,
			focusPushAuto: false,
			gain: false,
			imageTransmission: false,
			install: false,
			iris: false,
			night: false,
			ois: false,
			panTiltLimit: false,
			panTiltPosition: false,
			pedestal: false,
			preset: 9,
			presetSpeed: false,
			presetTime: false,
			pull: {
				ptz: ['O', 'DA', 'PE00', 'PE01', 'PE02', 'S'],
				cam: ['QAW', 'QBR', 'QRS', 'QSA:87', 'QSE:71'],
				web: false,
			},
			recordSD: false,
			restart: false,
			shutter: false,
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
			whiteBalance: { dropdown: e.ENUM_WHITEBALANCE_HE2 },
			zoom: false,
		},
	},
	{
		// Specific for the HE40 series
		id: 'HE40',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaPhase: false,
			colorGain: { cmd: { red: 'ORG', blue: 'OBG' }, offset: 0x1e, limit: 30, step: 1, hexlen: 2 },
			colorPedestal: false,
			colorTemperature: { index: { cmd: 'OSD:B1', dropdown: e.ENUM_COLOR_TEMPERATURE_LINEAR } },
			drs: { dropdown: e.ENUM_DRS_OFF_LOW_HIGH },
			errorCamera: false,
			filter: false,
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_HE40 },
			pedestal: { cmd: 'OTD', offset: 0x1e, limit: 30, step: 3, hexlen: 2 },
			poll: { ptz: false, cam: ['QSD:4F'], web: ['get_state'] },
			presetTime: false,
			pull: {
				ptz: [
					'APC',
					'O',
					'D6',
					'DA',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'LPI',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'RER',
					'S',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBR',
					'QCG',
					'QGB',
					'QGR',
					'QGU',
					'QIS',
					'QRS',
					'QSA:87',
					'QSD:3A',
					'QSD:B1',
					'QSE:33',
					'QSE:71',
					'QSH',
					'QTD',
				],
				web: false,
			},
			shutter: { cmd: 'OSH', dropdown: e.ENUM_SHUTTER_HE40 },
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AW-HE50 camera
		id: 'HE50',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaPhase: false,
			colorGain: { cmd: { red: 'ORG', blue: 'OBG' }, offset: 0x1e, limit: 30, step: 1, hexlen: 2 },
			colorPedestal: false,
			colorTemperature: false,
			drs: { dropdown: e.ENUM_DRS_OFF_LOW_HIGH },
			errorCamera: false,
			filter: false,
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_HE50 },
			imageTransmission: false,
			ois: false,
			pedestal: { cmd: 'OTD', offset: 0x1e, limit: 30, step: 3, hexlen: 2 },
			presetTime: false,
			poll: { ptz: false, cam: ['QSD:4F'], web: false },
			pull: {
				ptz: [
					'APC',
					'O',
					'D6',
					'DA',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'LPI',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'RER',
					'S',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBR',
					'QCG',
					'QGB',
					'QGR',
					'QGU',
					'QRS',
					'QSA:87',
					'QSD:3A',
					'QSE:33',
					'QSE:71',
					'QSH',
					'QTD',
				],
				web: false,
			},
			recordSD: false,
			restart: false,
			shutter: { cmd: 'OSH', dropdown: e.ENUM_SHUTTER_HE40 },
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AW-HE120 camera
		id: 'HE120',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaPhase: false,
			colorTemperature: false,
			errorCamera: { cmd: 'QER', bits: ['Fan'] },
			filter: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_HE120 },
			imageTransmission: false,
			night: false,
			ois: false,
			pedestal: { cmd: 'OTP', offset: 0x96, limit: 150, step: 1, hexlen: 3 },
			presetTime: false,
			poll: { ptz: false, cam: ['QSD:4F'], web: false },
			pull: {
				ptz: [
					'APC',
					'O',
					'DA',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'LPI',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'RER',
					'S',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBI',
					'QBP',
					'QBR',
					'QCG',
					'QER',
					'QFT',
					'QGU',
					'QRI',
					'QRP',
					'QRS',
					'QSA:87',
					'QSD:3A',
					'QSE:33',
					'QSE:71',
					'QSH',
					'QTP',
				],
				web: false,
			},
			recordSD: false,
			restart: false,
			shutter: { cmd: 'OSH', dropdown: e.ENUM_SHUTTER_HE120 },
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AW-HE130 camera
		id: 'HE130',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_40 },
			chromaPhase: false,
			colorPedestal: { cmd: { red: 'ORP', blue: 'OBP' }, offset: 0x96, limit: 100, step: 1, hexlen: 3 },
			colorTemperature: { index: { cmd: 'OSD:B1', dropdown: e.ENUM_COLOR_TEMPERATURE_NONLINEAR } },
			errorCamera: false,
			filter: { dropdown: e.ENUM_FILTER_2 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_HE130 },
			imageTransmission: { cmd: 'camera?resolution=320' },
			pedestal: { cmd: 'OTP', offset: 0x96, limit: 150, step: 1, hexlen: 3 },
			presetTime: false,
			poll: { ptz: false, cam: ['QSD:4F'], web: false },
			pull: {
				ptz: [
					'APC',
					'O',
					'D6',
					'DA',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'LPI',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'RER',
					'S',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBI',
					'QBP',
					'QBR',
					'QFT',
					'QGU',
					'QIS',
					'QRI',
					'QRP',
					'QRS',
					'QSA:87',
					'QSD:3A',
					'QSD:B0',
					'QSD:B1',
					'QSE:33',
					'QSE:71',
					'QSH',
					'QTP',
				],
				web: false,
			},
			recordSD: false,
			restart: false,
			shutter: { cmd: 'OSH', dropdown: e.ENUM_SHUTTER_HE130 },
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AW-HR140 camera
		id: 'HR140',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 4, min: -40, max: 12, step: 1 },
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_40 },
			chromaPhase: false,
			colorPedestal: { cmd: { red: 'ORP', blue: 'OBP' }, offset: 0x96, limit: 100, step: 1, hexlen: 3 },
			colorTemperature: { index: { cmd: 'OSD:B1', dropdown: e.ENUM_COLOR_TEMPERATURE_NONLINEAR } },
			errorCamera: { cmd: 'QER', bits: ['Fan'] },
			filter: { dropdown: e.ENUM_FILTER_2 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_HR140 },
			imageTransmission: { cmd: 'camera?resolution=320' }, // no view.cgi, see HE130
			ois: { dropdown: e.ENUM_OIS_HR140 },
			pedestal: { cmd: 'OTP', offset: 0x96, limit: 150, step: 1, hexlen: 3 },
			presetTime: false,
			poll: { ptz: false, cam: ['QSD:4F'], web: false },
			pull: {
				ptz: [
					'APC',
					'O',
					'D6',
					'DA',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'LPI',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'RER',
					'S',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBI',
					'QBP',
					'QBR',
					'QER',
					'QFT',
					'QGU',
					'QIS',
					'QRI',
					'QRP',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSA:D5:1',
					'QSA:D5:2',
					'QSA:D5:3',
					'QSD:3A',
					'QSD:B0',
					'QSD:B1',
					'QSE:33',
					'QSE:71',
					'QSH',
					'QTP',
				],
				web: false,
			},
			recordSD: false,
			restart: false,
			shutter: { cmd: 'OSH', dropdown: e.ENUM_SHUTTER_HE130 },
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AK-UBX100 box camera
		id: 'UBX100',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_UBX100 },
			chromaPhase: false,
			colorGain: {
				cmd: { red: 'OSL:36', blue: 'OSL:38', green: 'OSL:37' },
				offset: 0x800,
				limit: 1000,
				step: 1,
				hexlen: 3,
			},
			colorPedestal: {
				cmd: { red: 'OSG:4C', blue: 'OSG:4E', green: 'OSG:4D' },
				offset: 0x800,
				limit: 800,
				step: 1,
				hexlen: 3,
			},
			colorTemperature: false,
			dnr: { dropdown: e.ENUM_OFF_ON },
			drs: false,
			error: false,
			errorCamera: { cmd: 'QSI:46', bits: ['Fan', 'High Temperature'] },
			filter: { dropdown: e.ENUM_FILTER_3 },
			focus: false, // special implementation req. 'OSM:77', 'OZP'
			focusAuto: false,
			focusPushAuto: false,
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UBX100 },
			install: false,
			iris: { cmd: 'ORV', transport: 'cam', offset: 0x0, max: 0x3ff, step: 0xa },
			irisF: true,
			irisFollowPosition: false,
			night: false,
			ois: false,
			panTilt: false,
			panTiltPosition: false,
			panTiltLimit: false, // box camera, no pan/tilt head
			pedestal: { cmd: 'OSJ:0F', offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			power: false,
			preset: false,
			presetScope: false,
			presetSpeed: false,
			presetTime: false,
			pull: {
				ptz: false,
				cam: [
					'QBR',
					'QFT',
					'QGU',
					'QIF',
					'QLG',
					'QLR',
					'QLY',
					'QRS',
					'QRV',
					'QSA:87',
					'QSD:3A',
					'QSD:B0',
					'QSG:4C',
					'QSG:4D',
					'QSG:4E',
					'QSI:18',
					'QSI:30',
					'QSI:46',
					'QSJ:03',
					'QSJ:06',
					'QSJ:0F',
					'QSL:36',
					'QSL:37',
					'QSL:38',
				],
				web: false,
			},
			recordSD: false,
			restart: false,
			shootingMode: { cmd: 'OSI:30', dropdown: e.ENUM_SHOOTING_MODE },
			shutter: { cmd: 'OSJ:03', inc: 'OSJ:04', dec: 'OSJ:05', dropdown: e.ENUM_SHUTTER_ADV_UE20 }, // OFF/STEP/SYNCHRO, no ELC
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			trackingAuto: false,
			whiteBalance: true, // OWS/OAS execute, but no OAW mode dropdown
			zoom: false, // special implementation req. 'OSM:77', 'OZP'
		},
	},
	{
		// Specific for the AK-UB300 camera
		id: 'UB300',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_40 },
			chromaPhase: false,
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 1000, step: 1, hexlen: 3 },
			colorPedestal: { cmd: { red: 'OSG:4C', blue: 'OSG:4E' }, offset: 0x800, limit: 800, step: 1, hexlen: 3 },
			colorTemperature: { advanced: { inc: 'OSI:1E', dec: 'OSI:1F', maxStep: 1 } }, // one notch per command
			dnr: { dropdown: e.ENUM_OFF_ON },
			drs: false,
			error: false,
			errorCamera: { cmd: 'QER', bits: ['Fan'] },
			filter: { dropdown: e.ENUM_FILTER_3 },
			focus: false,
			focusAuto: false,
			focusPushAuto: false,
			gain: { cmd: 'OGS', dropdown: e.ENUM_GAIN_UB300 },
			install: false,
			iris: { cmd: 'ORV', transport: 'cam', offset: 0x0, max: 0x3ff, step: 0xa },
			irisF: true,
			irisFollowPosition: false,
			night: false,
			ois: false,
			panTilt: false,
			panTiltPosition: false,
			panTiltLimit: false, // box camera, no pan/tilt head
			pedestal: { cmd: 'OSG:4A', offset: 0x80, limit: 99, step: 1, hexlen: 2 },
			power: false,
			preset: false,
			presetSpeed: false,
			presetTime: false,
			pull: {
				ptz: false,
				cam: [
					'QBR',
					'QER',
					'QFT',
					'QGS',
					'QIF',
					'QLG',
					'QLR',
					'QRS',
					'QRV',
					'QSA:87',
					'QSD:3A',
					'QSD:B0',
					'QSG:39',
					'QSG:3A',
					'QSG:4A',
					'QSG:4C',
					'QSG:4E',
					'QSI:18',
					'QSI:20',
					'QSI:30',
				],
				web: false,
			},
			recordSD: false,
			restart: false,
			shootingMode: { cmd: 'OSI:30', dropdown: e.ENUM_SHOOTING_MODE },
			shutter: false, // special implementation req. 'OSG:5D', e.ENUM_SHUTTER_UB300
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally3: false,
			trackingAuto: false,
			version: false,
			whiteBalance: true, // no white balance mode
			zoom: false, // special implementation req. 'HZT', 'HZW', 'HZS', 'LZS:xx'
		},
	},
	{
		// Specific for the AK-UB50 / AK-UB10 box cameras.
		id: 'UB50',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: false,
			chromaPhase: false,
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: false,
			colorTemperature: {
				advanced: { inc: 'OSI:1E', dec: 'OSI:1F', set: 'OSI:20', min: 2500, max: 10000, maxStep: 10 },
			},
			dnr: false,
			drs: false,
			error: false,
			errorCamera: { cmd: 'QSI:46', bits: ['Fan', 'High Temperature'] },
			filter: false,
			focus: false, // special implementation req. 'HFF', 'HFN', 'HFS', 'LFP:xxx', 'LFS:x'
			focusAuto: false,
			gain: { cmd: 'OSL:25', dropdown: e.ENUM_GAIN_UB50 },
			install: false,
			iris: { cmd: 'ORV', transport: 'cam', offset: 0x0, max: 0x3ff, step: 0xa },
			irisF: true,
			irisFollowPosition: false,
			night: false,
			ois: false,
			panTilt: false,
			panTiltPosition: false,
			panTiltLimit: false, // box camera, no pan/tilt head
			pedestal: { cmd: 'OSJ:0F', offset: 0x800, limit: 15, step: 1, hexlen: 3 },
			power: false,
			pull: {
				ptz: false,
				cam: [
					'QAW',
					'QBR',
					'QIF',
					'QLR',
					'QRS',
					'QRV',
					'QSA:87',
					'QSG:39',
					'QSG:3A',
					'QSI:18',
					'QSI:20',
					'QSI:46',
					'QSJ:0F',
					'QSL:25',
				],
				web: false,
			},
			preset: false,
			presetSpeed: false,
			presetTime: false,
			recordSD: false,
			restart: false,
			shutter: false,
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false, // TLY is query only
			trackingAuto: false,
			version: false,
			whiteBalance: { dropdown: e.ENUM_WHITEBALANCE_UB50, confirm: { 2: '1', 3: '2' } },
			zoom: false, // special implementation req. 'HZT', 'HZW', 'HZS', 'LZP:xxx', 'LZS:x'
		},
	},
	{
		// Specific for the AW-UE5 camera
		id: 'UE5',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: { cmd: 'OCG', dropdown: e.ENUM_CHROMA_LEVEL_10 },
			chromaPhase: false,
			colorGain: false,
			colorPedestal: false,
			colorTemperature: false,
			drs: { dropdown: e.ENUM_OFF_ON },
			error: false, // no rER
			errorCamera: false,
			filter: false,
			focusAuto: false,
			focusPushAuto: false,
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE4 },
			irisFollowPosition: false,
			night: false,
			ois: false,
			panTiltLimit: false,
			panTiltPosition: false,
			pedestal: false,
			poll: { ptz: false, cam: false, web: ['get_rtmp_status'] },
			presetScope: false,
			presetSpeed: false,
			presetTime: false,
			pull: {
				ptz: ['O', 'AXF', 'AXI', 'AXZ', 'INS', 'PE00', 'PE01', 'PE02', 'S', 'TAA'],
				cam: ['QAW', 'QBR', 'QCG', 'QGU', 'QRS', 'QSA:87', 'QSD:3A', 'QSE:33', 'QSJ:03', 'QSJ:06'],
				web: false,
			},
			recordSD: false,
			shutter: { cmd: 'OSJ:03', inc: 'OSJ:04', dec: 'OSJ:05', dropdown: e.ENUM_SHUTTER_ADV_UE4 },
			streamSRT: false,
			streamTS: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AW-UE4 camera
		id: 'UE4',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaLevel: { cmd: 'OCG', dropdown: e.ENUM_CHROMA_LEVEL_10 },
			chromaPhase: false,
			colorGain: false,
			colorPedestal: false,
			colorTemperature: false,
			drs: { dropdown: e.ENUM_OFF_ON },
			error: false,
			errorCamera: false,
			filter: false,
			focus: false,
			focusAuto: false,
			focusPushAuto: false,
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE4 },
			iris: false,
			irisAuto: false, // supports only 1 (Auto)
			irisFollowPosition: false,
			night: false,
			ois: false,
			panTiltLimit: false,
			panTiltPosition: false,
			pedestal: false,
			poll: { ptz: false, cam: false, web: ['get_rtmp_status'] },
			presetScope: false, // has presets, but no OSE:71 to scope what a recall restores
			presetSpeed: false,
			presetTime: false,
			pull: {
				ptz: ['O', 'AXZ', 'INS', 'PE00', 'PE01', 'PE02', 'S', 'TAA'],
				cam: ['QAW', 'QBR', 'QCG', 'QGU', 'QSA:87', 'QSD:3A', 'QSE:33', 'QSJ:03', 'QSJ:06'],
				web: false,
			},
			recordSD: false,
			shutter: { cmd: 'OSJ:03', inc: 'OSJ:04', dec: 'OSJ:05', dropdown: e.ENUM_SHUTTER_ADV_UE4 },
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the UE20/HE20
		id: 'UE20',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 1, min: -36, max: 12, step: 3 },
			chromaLevel: { cmd: 'OCG', dropdown: e.ENUM_CHROMA_LEVEL_10 },
			chromaPhase: false,
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 30, step: 1, hexlen: 3 },
			colorPedestal: false,
			colorTemperature: false,
			drs: { dropdown: e.ENUM_OFF_ON },
			error: false,
			errorCamera: false,
			filter: false,
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE100 },
			irisF: true,
			night: false,
			ois: false,
			panTiltPosition: false,
			pedestal: { cmd: 'OSJ:0F', offset: 0x800, limit: 10, step: 1, hexlen: 3 },
			poll: { ptz: false, cam: ['QSD:4F'], web: ['get_rtmp_status'] },
			presetThumbnails: true,
			presetTime: false,
			pull: {
				ptz: ['O', 'INS', 'LC1', 'LC2', 'LC3', 'LC4', 'LPI', 'PE00', 'PE01', 'PE02', 'PST', 'S', 'TAA', 'UPVS'],
				cam: [
					'QAF',
					'QAW',
					'QBR',
					'QCG',
					'QGU',
					'QIF',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSD:3A',
					'QSE:33',
					'QSE:71',
					'QSG:39',
					'QSG:3A',
					'QSJ:03',
					'QSJ:06',
					'QSJ:0F',
				],
				web: false,
			},
			recordSD: false,
			shutter: { cmd: 'OSJ:03', inc: 'OSJ:04', dec: 'OSJ:05', dropdown: e.ENUM_SHUTTER_ADV_UE20 },
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the UE50/40
		id: 'UE50',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 2, min: -36, max: 12, step: 3 },
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_99 },
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: false,
			filter: false,
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE100 },
			irisF: true,
			night: false,
			poll: { ptz: false, cam: ['QSD:4F'], web: ['get_rtmp_status', 'get_srt_status', 'get_ts_status'] },
			presetThumbnails: true,
			pull: {
				ptz: [
					'O',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'PTG',
					'PTV',
					'RER',
					'S',
					'TAA',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBR',
					'QSD:B0',
					'QIF',
					'QIS',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSA:D5:1',
					'QSD:3A',
					'QSE:33',
					'QSE:71',
					'QSG:39',
					'QSG:3A',
					'QSI:46',
					'QSJ:0B',
					'QSJ:0F',
					'QSJ:29',
					'QSL:B6',
					'QSL:B7',
					'QSL:BB',
				],
				web: false,
			},
			recordSD: false,
			tally3: false,
		},
	},
	{
		// Specific for the UE70 series
		id: 'UE70',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: false,
			chromaPhase: false,
			colorGain: { cmd: { red: 'ORG', blue: 'OBG' }, offset: 0x1e, limit: 30, step: 1, hexlen: 2 },
			colorPedestal: false,
			colorTemperature: { index: { cmd: 'OSD:B1', dropdown: e.ENUM_COLOR_TEMPERATURE_LINEAR } },
			drs: { dropdown: e.ENUM_DRS_OFF_LOW_HIGH },
			errorCamera: false,
			filter: { dropdown: e.ENUM_FILTER_3A },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_HE40 },
			pedestal: { cmd: 'OTD', offset: 0x1e, limit: 30, step: 3, hexlen: 2 },
			poll: { ptz: false, cam: ['QSD:4F'], web: ['get_state'] },
			presetTime: false,
			pull: {
				ptz: [
					'APC',
					'O',
					'D6',
					'DA',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'LPI',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'RER',
					'S',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBR',
					'QCG',
					'QFT',
					'QGB',
					'QGR',
					'QGU',
					'QIS',
					'QRS',
					'QSA:87',
					'QSD:3A',
					'QSD:B1',
					'QSE:33',
					'QSE:71',
					'QSH',
					'QTD',
				],
				web: false,
			},
			shutter: { cmd: 'OSH', dropdown: e.ENUM_SHUTTER_HE40 },
			streamRTMP: false,
			streamSRT: false,
			streamTS: false,
			tally2: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the UE80
		id: 'UE80',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 2, min: -36, max: 12, step: 3 },
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_99 },
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: false,
			filter: { dropdown: e.ENUM_FILTER_3A },
			filterFollow: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE100 },
			irisF: true,
			ois: { dropdown: e.ENUM_OIS_UE80 },
			poll: { ptz: false, cam: ['QSD:4F'], web: ['get_rtmp_status', 'get_srt_status', 'get_ts_status'] },
			presetThumbnails: true,
			pull: {
				ptz: [
					'O',
					'D6',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'PTG',
					'PTV',
					'RER',
					'S',
					'TAA',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBR',
					'QIF',
					'QIS',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSA:D5:1',
					'QSD:3A',
					'QSD:B0',
					'QSE:33',
					'QSE:71',
					'QSG:39',
					'QSG:3A',
					'QSI:46',
					'QSJ:0B',
					'QSJ:0F',
					'QSJ:29',
					'QSJ:D2',
					'QSL:B6',
					'QSL:B7',
					'QSL:BB',
				],
				web: false,
			},
			recordSD: false,
			tally3: false,
		},
	},
	{
		// Specific for the UE100 camera
		id: 'UE100',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 1, min: -36, max: 12, step: 3 },
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_99 },
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: {
				cmd: { red: 'ORP', blue: 'OBP', green: 'OSJ:10' },
				offset: 0x96,
				limit: 100,
				step: 1,
				hexlen: 3,
			},
			filter: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE100 },
			irisF: true,
			ois: { dropdown: e.ENUM_OIS_UE100 },
			poll: {
				ptz: false,
				cam: ['QIF', 'QSD:4F', 'QSD:B0', 'QSI:46', 'QSJ:10'],
				web: ['get_rtmp_status', 'get_srt_status', 'get_ts_status'],
			},
			presetThumbnails: true,
			pull: {
				ptz: [
					'O',
					'D6',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'PTG',
					'PTV',
					'RER',
					'S',
					'TAA',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBP',
					'QBR',
					'QIF',
					'QIS',
					'QRP',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSD:3A',
					'QSD:B0',
					'QSE:33',
					'QSE:71',
					'QSG:39',
					'QSG:3A',
					'QSI:30',
					'QSJ:0B',
					'QSJ:0F',
					'QSJ:10',
					'QSJ:29',
				],
				web: false,
			},
			recordSD: false,
			shootingMode: { cmd: 'OSI:30', dropdown: e.ENUM_SHOOTING_MODE },
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AW-UR100 camera
		id: 'UR100',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 2, min: -30, max: 20, step: 1 },
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_99 },
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: {
				cmd: { red: 'ORP', blue: 'OBP', green: 'OSJ:10' },
				offset: 0x96,
				limit: 100,
				step: 1,
				hexlen: 3,
			},
			filter: { dropdown: e.ENUM_FILTER_3A },
			filterFollow: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE100 },
			irisF: true,
			ois: { dropdown: e.ENUM_OIS_UE100 },
			poll: {
				ptz: false,
				cam: ['QIF', 'QSD:4F', 'QSD:B0', 'QSI:46', 'QSJ:10'],
				web: ['get_rtmp_status', 'get_srt_status', 'get_ts_status'],
			},
			presetThumbnails: true,
			pull: {
				ptz: [
					'O',
					'D6',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'PTG',
					'PTV',
					'RER',
					'S',
					'TAA',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBP',
					'QBR',
					'QIF',
					'QIS',
					'QRP',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSA:D5:1',
					'QSD:3A',
					'QSD:B0',
					'QSE:33',
					'QSE:71',
					'QSG:39',
					'QSG:3A',
					'QSJ:0B',
					'QSJ:0F',
					'QSJ:10',
					'QSJ:29',
					'QSJ:D2',
				],
				web: false,
			},
			recordSD: false,
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the UE150 series
		id: 'UE150',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 1, min: -36, max: 12, step: 3 },
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_99 },
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: {
				cmd: { red: 'ORP', blue: 'OBP', green: 'OSJ:10' },
				offset: 0x96,
				limit: 100,
				step: 1,
				hexlen: 3,
			},
			filter: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE150 },
			irisF: true,
			poll: {
				ptz: false,
				cam: ['QIF', 'QSD:4F', 'QSD:B0', 'QSI:46', 'QSJ:10', 'QSA:D5:0'],
				web: ['get_rtmp_status', 'get_srt_status', 'get_ts_status'],
			},
			presetThumbnails: true,
			pull: {
				ptz: [
					'O',
					'D6',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'PTG',
					'PTV',
					'RER',
					'S',
					'TAA',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBP',
					'QBR',
					'QIF',
					'QIS',
					'QRP',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSD:3A',
					'QSD:B0',
					'QSE:33',
					'QSE:71',
					'QSG:39',
					'QSG:3A',
					'QSI:30',
					'QSJ:0B',
					'QSJ:0F',
					'QSJ:10',
					'QSJ:29',
				],
				web: false,
			},
			recordSD: false,
			shootingMode: { cmd: 'OSI:30', dropdown: e.ENUM_SHOOTING_MODE },
			tally3: false,
			trackingAuto: false,
		},
	},
	{
		// Specific for the AW-UE150A camera
		id: 'UE150A',
		capabilities: {
			...BASE_CAPABILITIES,
			audioVolumeLevel: { maxch: 1, min: -36, max: 12, step: 3 },
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_99 },
			colorGain: { cmd: { red: 'OSG:39', blue: 'OSG:3A' }, offset: 0x800, limit: 200, step: 1, hexlen: 3 },
			colorPedestal: {
				cmd: { red: 'ORP', blue: 'OBP', green: 'OSJ:10' },
				offset: 0x96,
				limit: 100,
				step: 1,
				hexlen: 3,
			},
			filter: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE150 },
			irisF: true,
			poll: {
				ptz: false,
				cam: ['QIF', 'QSD:4F', 'QSD:B0', 'QSI:46', 'QSJ:10', 'QSA:D5:0'],
				web: ['get_rtmp_status', 'get_srt_status', 'get_ts_status'],
			},
			presetThumbnails: true,
			pull: {
				ptz: [
					'O',
					'D6',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'PTG',
					'PTV',
					'RER',
					'S',
					'TAA',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBP',
					'QBR',
					'QIF',
					'QIS',
					'QRP',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSD:3A',
					'QSD:B0',
					'QSE:33',
					'QSE:71',
					'QSG:39',
					'QSG:3A',
					'QSI:30',
					'QSJ:0B',
					'QSJ:0F',
					'QSJ:10',
					'QSJ:29',
					'QSL:B6',
					'QSL:B7',
					'QSL:BB',
				],
				web: false,
			},
			recordSD: false,
			shootingMode: { cmd: 'OSI:30', dropdown: e.ENUM_SHOOTING_MODE },
			tally3: false,
		},
	},
	{
		// Specific for the AW-UE160 camera
		id: 'UE160',
		capabilities: {
			...BASE_CAPABILITIES,
			chromaLevel: { cmd: 'OSD:B0', dropdown: e.ENUM_CHROMA_PCT_40 },
			chromaPhase: false,
			colorGain: {
				cmd: { red: 'OSL:36', blue: 'OSL:38', green: 'OSL:37' },
				offset: 0x800,
				limit: 1000,
				step: 1,
				hexlen: 3,
			},
			colorPedestal: {
				cmd: { red: 'OSG:4C', blue: 'OSG:4E', green: 'OSG:4D' },
				offset: 0x800,
				limit: 800,
				step: 1,
				hexlen: 3,
			},
			dnr: { dropdown: e.ENUM_OFF_ON },
			drs: false,
			filter: { dropdown: e.ENUM_FILTER_3 },
			gain: { cmd: 'OGU', dropdown: e.ENUM_GAIN_UE160 },
			irisF: true,
			ois: { dropdown: e.ENUM_OIS_UE160 },
			poll: { ptz: false, cam: ['QSD:4F'], web: ['get_rtmp_status', 'get_srt_status', 'get_ts_status'] },
			presetThumbnails: true,
			pull: {
				ptz: [
					'O',
					'D6',
					'INS',
					'LC1',
					'LC2',
					'LC3',
					'LC4',
					'PE00',
					'PE01',
					'PE02',
					'PST',
					'PTG',
					'PTV',
					'RER',
					'S',
					'TAA',
					'UPVS',
				],
				cam: [
					'QAF',
					'QAW',
					'QBR',
					'QIF',
					'QIS',
					'QRS',
					'QSA:87',
					'QSA:D5:0',
					'QSA:D5:1',
					'QSD:3A',
					'QSD:B0',
					'QSE:71',
					'QSG:4C',
					'QSG:4D',
					'QSG:4E',
					'QSI:30',
					'QSI:46',
					'QSJ:0F',
					'QSJ:29',
					'QSL:36',
					'QSL:37',
					'QSL:38',
				],
				web: false,
			},
			recordSD: false,
			shootingMode: { cmd: 'OSI:30', dropdown: e.ENUM_SHOOTING_MODE },
			trackingAuto: false,
		},
	},
]
